modLoader="javafml"
loaderVersion="[50,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
credits="${mod_credits}"
displayURL="${mod_source}"
logoFile="logo.png"
authors="${mod_authors}"
description="${mod_description}"


[[dependencies.legacy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,)"
    ordering="NONE"
    side="BOTH"




