modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
credits="${mod_credits}"
displayURL="${mod_source}"
logoFile="logo.png"
authors="${mod_authors}"
description="${mod_description}"
[[mixins]]
config="${mod_id}.mixins.json"
[[mixins]]
config="${mod_id}-common.mixins.json"

[[dependencies.legacy]]
modId="minecraft"
type="required"
versionRange="[1.20.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.legacy]]
modId="architectury"
type="required"
versionRange="[${architectury_version},]"
ordering="NONE"
side="BOTH"
[[dependencies.legacy]]
modId="jei"
type="optional"
versionRange="[${jei_version},)"
ordering="NONE"
side="BOTH"




